# Generated by Django 5.2.6 on 2025-09-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_userprofile_access_id_userprofile_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
